stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:27.4.1
  services:
    - docker:27.4.1-dind
  script:
    - docker info
    - docker build -f Dockerfile . -t my-python-web-server
    - docker login --username $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag my-python-web-server $DOCKER_USER/my-python-web-server
    - docker push $DOCKER_USER/my-python-web-server
    - echo "End build stage"
  rules:
    - when: manual

test:
  stage: test
  image: docker:27.4.1
  services:
    - docker:27.4.1-dind
  script:
    - docker pull $DOCKER_USER/my-python-web-server
    - docker run -d --name my-python $DOCKER_USER/my-python-web-server
    - sleep 20
    - docker exec my-python /bin/bash -c 'curl localhost'
    - echo "End test stage"
  rules:
    - when: manual

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f kubernetes/my-python-deployment.yaml
    - kubectl apply -f kubernetes/my-python-lb-svc.yaml
    - echo "End deploy stage"
  rules:
    - when: manual