stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Build stage
build:
  stage: build
  image: docker:27.4.1
  services:
    - docker:27.4.1-dind
  script:
    - docker info
    - docker build -f Dockerfile . -t $IMAGE_NAME
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    - docker push $IMAGE_NAME
    - echo "End build stage"

# Test stage
test:
  stage: test
  image: docker:27.4.1
  services:
    - docker:27.4.1-dind
  script:
    - docker info
    - docker pull $IMAGE_NAME
    - docker run -d --name my-python $IMAGE_NAME
    - sleep 10
    - docker exec my-python curl localhost
    - echo "End test stage"

# Deploy stage
deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl create secret generic weather-secret --from-literal=API_KEY="$API_KEY" --dry-run=client -o yaml | kubectl apply -f -
    - sed "s|__IMAGE_NAME__|$IMAGE_NAME|g" kubernetes/my-python-deployment.yaml | kubectl apply -f -
    - kubectl apply -f kubernetes/my-python-hpa.yaml
    - kubectl apply -f kubernetes/my-python-do-lb-service.yaml
    - kubectl rollout restart deployment my-python
    - kubectl get pods
    - kubectl get events
    - kubectl top nodes || echo "Skipping metrics"
    - echo "End deploy stage"




