apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python
          image: tomafcsb/my-python-web-server
          ports:
            - containerPort: 80
          env:
            - name: API_KEY
              value: "${API_KEY}"  
            - name: PORT
              value: "80"
          resources:
            limits:
              cpu: "100m"

